spring:
  datasource:
    # url: jdbc:h2:mem:chatDB;DB_CLOSE_DELAY=-1;MODE=MYSQL
    # url: jdbc:h2:tcp://localhost/~/chatDB
    # username: sa
    # password:
    #driver-class-name: org.h2.Driver

    url: jdbc:mariadb://localhost:3306/chat
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect # MariaDB103Dialect
    #database-platform: org.hibernate.dialect.H2Dialect # MariaDB103Dialect
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      # mode: always

logging:
  level:
    org.apache.coyote.http11: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace